#!/bin/bash

#
# © 2023 Joey Smalen ("Smally", "QSmally")
#
# Command usage:
#   <Submodule>/Scripts/generate <target> [destination]
#
# <target>: source directory of the document target, finds starting file which
#   starts with the '00-' prefix as per convention. The name of the directory of
#   the source files (the target) will be the name of the rendered document.
# [destination]: destination directory of the rendered PDF, and if it isn't
#   supplied, 'Rendered Documents'. If none are available, puts it in the pwd.
#
# Note: if a file with the '.bib' suffix and an auxilary file are present, the
#   'bibtex' command will be ran before 'pdflatex' will.
#
# <Submodule>/Scripts/generate .
# <Submodule>/Scripts/generate Report/
# <Submodule>/Scripts/generate Documentation/ Output\ Files/
#

set -e

if [ $# -eq 0 ] || [ ! -d "$1" ]; then
    echo "error: input a path to a directory"
    exit 1
fi

START_FILE=$(find "$1" -maxdepth 1 -name '00-*.tex')

if [ -z "$START_FILE" ]; then
    echo "error: no 00-*.tex starting file found"
    exit 1
fi

RESOLVED_PATH=$(dirname "$(readlink -f "$START_FILE")")
JOB=$(basename "$RESOLVED_PATH")
OUTPUT_FILE=$JOB.pdf

echo "info: input directory = $1"
echo "info: starting file   = $(basename "$START_FILE")"
echo "info: output file     = $OUTPUT_FILE"

CWD=$(pwd)
BIB_FILE=$(find "$1" -maxdepth 1 -name '*.bib')

if [ ! -z "$BIB_FILE" ] && [ -e "$RESOLVED_PATH/Compilation/$JOB.aux" ]; then
    echo "mark: bibTeX routine"
    echo "info: bib file        = $(basename "$BIB_FILE")"

    cd "$RESOLVED_PATH/Compilation/"
    cp "$RESOLVED_PATH/$(basename "$BIB_FILE")" .
    bibtex "$JOB.aux" > /dev/null
fi

cd "$RESOLVED_PATH"
mkdir -p Compilation/

echo "mark: TeX compile"

pdflatex \
    -output-directory=Compilation \
    -jobname="$JOB" \
    -interaction=nonstopmode \
    "$(basename "$START_FILE")" > /dev/null
if [ ! -e "$RESOLVED_PATH/Compilation/$OUTPUT_FILE" ]; then
    exit 1
fi

cd $CWD

OUTPUT_DIRECTORY=${2:-'Rendered Documents'}
[ -d "$OUTPUT_DIRECTORY" ] && OUTPUT=$OUTPUT_DIRECTORY || OUTPUT=.
cp "$RESOLVED_PATH/Compilation/$OUTPUT_FILE" "$OUTPUT"

echo "done; no errors"
